import type { NavigationConfig } from "../types/navigation";

const primarySurfaces = ["primary", "mobile", "sitemap", "breadcrumb", "search"] as const;
const childSurfaces = ["mobile", "footer", "sitemap", "breadcrumb", "search"] as const;

export const navigationConfig = {
  items: [
    {
      id: "about",
      kind: "link",
      label: "About",
      href: "/#about",
      description: "A short introduction to how I think and work.",
      icon: "user",
      surfaces: ["primary", "mobile", "footer", "sitemap", "breadcrumb", "search"],
      order: 10,
    },
    {
      id: "work",
      kind: "menu",
      label: "Work",
      description: "Portfolio evidence, practical skills, and delivery experience.",
      icon: "briefcase",
      surfaces: primarySurfaces,
      order: 20,
      children: [
        {
          id: "skills",
          kind: "link",
          label: "Skills",
          href: "/#skills",
          description: "A practical, maintainable technology stack.",
          icon: "layers",
          surfaces: childSurfaces,
          order: 10,
        },
        {
          id: "experience",
          kind: "link",
          label: "Experience",
          href: "/#experience",
          description: "Professional experience focused on impact and growth.",
          icon: "timeline",
          surfaces: childSurfaces,
          order: 20,
        },
        {
          id: "projects",
          kind: "link",
          label: "Projects",
          href: "/projects",
          description: "Selected projects with real-world challenges and solutions.",
          icon: "folder",
          surfaces: childSurfaces,
          order: 30,
        },
      ],
      featured: {
        label: "Featured Project",
        title: "Project case studies",
        description: "A closer look at implementation decisions, tradeoffs, and measurable outcomes.",
        href: "/projects",
        icon: "folder",
        source: "manual",
      },
    },
    {
      id: "growth",
      kind: "menu",
      label: "Growth",
      href: "/growth",
      description: "Personal progress, learning habits, and durable interests.",
      icon: "trending-up",
      surfaces: ["primary", "mobile", "footer", "sitemap", "breadcrumb", "search"],
      order: 30,
      children: [
        {
          id: "achievements",
          kind: "link",
          label: "Achievements",
          href: "/growth/achievements",
          description: "Milestones that mark my progress.",
          icon: "award",
          surfaces: childSurfaces,
          order: 10,
        },
        {
          id: "books",
          kind: "link",
          label: "Books",
          href: "/growth/books",
          description: "Books that shaped how I think and work.",
          icon: "book",
          surfaces: childSurfaces,
          order: 20,
        },
        {
          id: "running",
          kind: "link",
          label: "Running",
          href: "/growth/running",
          description: "Consistency beyond the keyboard.",
          icon: "activity",
          surfaces: childSurfaces,
          order: 30,
        },
        {
          id: "learning-journey",
          kind: "link",
          label: "Learning Journey",
          href: "/growth/learning-journey",
          description: "Courses, experiments, and continuous learning.",
          icon: "map",
          surfaces: childSurfaces,
          order: 40,
        },
        {
          id: "certifications",
          kind: "link",
          label: "Certifications",
          href: "/growth/certifications",
          description: "Formal recognition of technical knowledge.",
          icon: "badge",
          surfaces: childSurfaces,
          order: 50,
        },
        {
          id: "languages",
          kind: "link",
          label: "Languages",
          href: "/growth/languages",
          description: "Communicating beyond code.",
          icon: "globe",
          surfaces: childSurfaces,
          order: 60,
        },
      ],
      featured: {
        label: "Featured Achievement",
        title: "Progress with direction",
        description: "A curated marker of growth that reflects consistency, learning, and craft.",
        href: "/growth/achievements",
        icon: "award",
        source: "manual",
      },
    },
    {
      id: "thoughts",
      kind: "menu",
      label: "Thoughts",
      href: "/thoughts",
      description: "Principles, references, and reflections from practice.",
      icon: "message-square",
      surfaces: ["primary", "mobile", "footer", "sitemap", "breadcrumb", "search"],
      order: 40,
      children: [
        {
          id: "principles",
          kind: "link",
          label: "Principles",
          href: "/thoughts/principles",
          description: "Ideas that guide my decisions.",
          icon: "compass",
          surfaces: childSurfaces,
          order: 10,
        },
        {
          id: "quotes",
          kind: "link",
          label: "Quotes",
          href: "/thoughts/quotes",
          description: "Words worth remembering.",
          icon: "quote",
          surfaces: childSurfaces,
          order: 20,
        },
        {
          id: "reflections",
          kind: "link",
          label: "Reflections",
          href: "/thoughts/reflections",
          description: "Lessons learned through experience.",
          icon: "spark",
          surfaces: childSurfaces,
          order: 30,
        },
      ],
      featured: {
        label: "Today's Principle",
        title: "Clarity over complexity",
        description: "A reminder to choose understandable systems before clever ones.",
        href: "/thoughts/principles",
        icon: "compass",
        source: "manual",
      },
    },
    {
      id: "blog",
      kind: "link",
      label: "Blog",
      href: "/blog",
      description: "Articles about engineering decisions, frontend work, and clear interfaces.",
      icon: "pen",
      surfaces: ["primary", "mobile", "footer", "sitemap", "breadcrumb", "search", "rss"],
      order: 50,
    },
    {
      id: "contact",
      kind: "link",
      label: "Contact",
      href: "/#contact",
      description: "Ways to start a conversation.",
      icon: "mail",
      surfaces: ["primary", "mobile", "footer", "sitemap", "breadcrumb", "search"],
      order: 60,
    },
  ],
  cta: {
    label: "Resume",
    href: "/resume",
    surfaces: ["primary", "mobile", "footer", "sitemap", "breadcrumb", "search"],
  },
} as const satisfies NavigationConfig;
